//
//  AppDelegate.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.1
//

import UIKit
import Batch
import AWSMobileHubHelper

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window: UIWindow?
    
    // Initialize ImageStore and start downloading data, pass to root VC
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        Batch.startWithAPIKey("DEV570BD07814AB0002DE2261E8E60")
        BatchPush.registerForRemoteNotifications()
        
        let manager = AWSContentManager.defaultContentManager()
        
        let navViewController = window!.rootViewController as! HypeNavViewController
        
        var storyboard = UIStoryboard(name: "Settings View", bundle:nil)
        let settingsViewController = storyboard.instantiateViewControllerWithIdentifier("settingsVC") as! SettingsViewController
        settingsViewController.settingsDelegate = navViewController
        navViewController.settingsViewController = settingsViewController
        
        storyboard = UIStoryboard(name: "Main Hype View", bundle:nil)
        let mainViewController = storyboard.instantiateViewControllerWithIdentifier("mainHypeView") as! MainViewController
        mainViewController.manager = manager
        
        navViewController.mainViewController = mainViewController
        
        storyboard = UIStoryboard(name: "Grid View", bundle:nil)
        let gridViewController = storyboard.instantiateViewControllerWithIdentifier("gridViewController") as! GridViewController
        gridViewController.manager = manager
        
        navViewController.gridViewController = gridViewController
        
        let keychainWrapper = KeychainWrapper.standardKeychainAccess()
        
        
        if let userName = keychainWrapper.stringForKey(Constants.USERKEY), password = keychainWrapper.stringForKey(Constants.PASSKEY){
            navViewController.userName = userName
            navViewController.password = password
        }
        
        

        
        return true
    }
    
    func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        // print("application application: \(application.description), openURL: \(url.absoluteURL), sourceApplication: \(sourceApplication)")
        return AWSMobileClient.sharedInstance.withApplication(application, withURL: url, withSourceApplication: sourceApplication, withAnnotation: annotation)
    }
    
    func applicationWillResignActive(application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
    }
    
    func applicationDidEnterBackground(application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }
    
    
    func applicationDidBecomeActive(application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
        AWSMobileClient.sharedInstance.applicationDidBecomeActive(application)
    }
    
    func applicationWillTerminate(application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
    
}

